version: "3.7"  # or another version that supports your requirements

services:
  kimai:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   target: prod
    image: kimai-dev:latest
    volumes:
      - data:/opt/kimai/var/data
      - plugins:/opt/kimai/var/plugins
    ports:
      - "8001:8001"  # Exposing Kimai on port 8001
    environment:
      - ADMINMAIL=${ADMIN_EMAIL}
      - ADMINPASS=${ADMIN_PASSWORD}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:3306/${DATABASE_NAME}?charset=utf8mb4&serverVersion=8.3.0
    restart: unless-stopped

volumes:
  data:
  plugins:
